gui:
  mouseEvents: true
  nerdFontsVersion: "3"
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  pagers:
    - colorArg: 'always'
      pager: 'delta --dark --paging=never'
os:
  editPreset: 'nvim'
keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<ctrl-q>'
    nextMatch: 'n'
    prevMatch: 'N'
    redo: '<ctrl-r>'
    undo: 'u'
