#!/usr/bin/env bash
# First we need to check if we have a git root to go to
if git status >/dev/null 2>/dev/null; then
  cd "$(git rev-parse --show-toplevel)" || exit 1
fi

CURRENT_DIR=$(pwd)

if [[ -f "${CURRENT_DIR}/Session.vim" ]]; then
  nvim -c 'silent source Session.vim'
elif yes_no 'No Vim Project Found. Create One? [Y/n] ' 'y'; then
  nvim -c 'Obsession | Explore'
fi
