[env]
TERM = "xterm-256color"

[general]
live_config_reload = true

[font]
size = 19

[font.normal]
family = "InconsolataGo Nerd Font Mono"
style = "Regular"

[font.bold]
style = "Bold"

[window]
blur = true
decorations = "Buttonless"
opacity = 0.95
option_as_alt = "Both"
padding = { x = 6, y = 6 }

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Off" }

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.cursor]
text = "#1d1f21"
cursor = "#c5c8c6"

[colors.selection]
text = "#1d1f21"
background = "#c5c8c6"

[colors.normal]
black = "#1d1f21"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#c5c8c6"

[colors.bright]
black = "#969896"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#ffffff"

[[keyboard.bindings]]
key = "Comma"
mods = "Command"

[keyboard.bindings.command]
args = ["-c", "open ~/.config/alacritty/alacritty.toml"]
program = "sh"
